services:
  php-value:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        USER_ID: '${WWWUSER:-1000}'
        GROUP_ID: '${WWWGROUP:-1000}'
        USER: '${USER:-whoami}'
    container_name: php-value
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
